/**
 * Bridges the bindings generated by `wrangler types` (into
 * worker-configuration.d.ts as `Cloudflare.Env`) onto the `CloudflareEnv`
 * interface that `@opennextjs/cloudflare`'s `getCloudflareContext()` expects.
 *
 * Re-run `npx wrangler types` after changing bindings in wrangler.jsonc.
 */
declare global {
  interface CloudflareEnv extends Cloudflare.Env {
    /**
     * Secrets — NOT in wrangler.jsonc (so they aren't committed), therefore not
     * picked up by `wrangler types`. Declared here manually.
     *
     * Local:      put them in `.dev.vars`
     * Production: `npx wrangler secret put <NAME>`
     */
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    /** HMAC secret for the Cal.com webhook (POST /api/meetings). */
    CAL_WEBHOOK_SECRET: string;
  }
}

export {};
