import Image from "next/image";

import { cn } from "@/lib/utils";

/**
 * The Axonill mark. Single source of truth for the logo image.
 *
 * `mark.png` is the trimmed, squared derivative of public/brand/Symbol_Logo.png
 * (generated by scripts/generate-icons.mjs) — the raw file is 251x151 with heavy
 * padding, so using it directly would shrink the mark to a fraction of its box.
 *
 * The source artwork is only ~95x133 real pixels, so keep rendered sizes at or
 * below ~64px. See CLAUDE.md → Logo & Assets.
 */
export const MARK_SRC = "/brand/mark.png";

export function BrandMark({
  size = 32,
  className,
  priority = false,
  interactive = false,
}: {
  size?: number;
  className?: string;
  /** Set on above-the-fold marks (navbar, loader). */
  priority?: boolean;
  /** Adds hover scale + cyan glow. Requires a `group` ancestor. */
  interactive?: boolean;
}) {
  return (
    <Image
      src={MARK_SRC}
      alt=""
      aria-hidden
      width={size}
      height={size}
      priority={priority}
      className={cn(
        "shrink-0 select-none object-contain",
        // drop-shadow follows the alpha silhouette (a box-shadow would render a
        // rectangle around the transparent PNG). Also stops the mark's light-grey
        // top face from washing out against the light background.
        "[filter:drop-shadow(0_1px_2px_rgba(15,23,42,0.18))]",
        interactive &&
          "transition-[filter,transform] duration-300 group-hover:scale-105 group-hover:[filter:drop-shadow(0_0_10px_rgba(6,182,212,0.55))]",
        className
      )}
    />
  );
}
